version: '2'
services:

  node-service:
    build:
      image: company-node-image
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    cached: true

  laravel-service:
    build:
      image: company-laravel-image
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - node-service
    cached: true

  laravel-codeship-service:
    build:
      image: company-laravel-codeship-image
      context: .
      dockerfile: ./docker/laravel/codeship/Dockerfile
    depends_on:
      - laravel-service
      - mysql-service
    environment:
      DB_HOST: mysql-service
      DB_DATABASE: docker
      DB_USERNAME: root
      DB_PASSWORD: docker
    volumes:
        - ./:/var/www/html
        - /var/www/html/vendor
    cached: true

  mysql-service:
    build:
      image: company-mysql-image
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: docker
    cached: true