version: '2'

services:

  company-ubuntu-service:
    container_name: company-ubuntu-container
    image: company-ubuntu-image
    build:
      context: .
      dockerfile: ./docker/Dockerfile.company-ubuntu
    entrypoint: /container/folder/docker/company-ubuntu/start.sh
    depends_on:
      - some-other-docker-service
    environment:
      SOME_VARIABLE: some_variable_string
    volumes:
      - ./:/container/folder
      - some-volume:/container/folder
    ports:
      - "8004:8004"
    restart: always
    networks:
      - default

volumes:
  some-volume:
networks:
  default: