# Cloud66 service settings
version: 2
services:
  laravel-service:
    git_url: insert_git_url
    git_branch: master
    ports:
    - container: 80
      http: 80
      https: 443
    command: "/var/www/docker/laravel/production/start.sh"
    use_habitus: true
    use_habitus_step: laravel-production-service
    habitus_params: --f /var/www/docker/laravel/production/build.yml
    health:
      ready:
        type: http
        endpoint: "/"
        protocol: http
        timeout: 300
        initial_delay: 2